/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feedback;

import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author SiD
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminlogin = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        adminuser = new javax.swing.JTextField();
        adminpass = new javax.swing.JPasswordField();
        sigu = new javax.swing.JButton();
        studentlogin = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        studentuser = new javax.swing.JTextField();
        studentpass = new javax.swing.JPasswordField();
        stulog = new javax.swing.JButton();
        fresherquestion = new javax.swing.JFrame();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        qname = new javax.swing.JTextField();
        qcourse = new javax.swing.JTextField();
        qmail = new javax.swing.JTextField();
        qphone = new javax.swing.JTextField();
        question = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        qdesc = new javax.swing.JTextArea();
        qsubmit = new javax.swing.JButton();
        qlbdesc = new javax.swing.JLabel();
        qlbmail = new javax.swing.JLabel();
        qlbphone = new javax.swing.JLabel();
        admin = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        feedbacktable = new javax.swing.JTable();
        lb = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        freshertable = new javax.swing.JTable();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        student = new javax.swing.JFrame();
        jLabel25 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        freg = new javax.swing.JTextField();
        fabout = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        fcomment = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        fimpro = new javax.swing.JTextArea();
        frb5 = new javax.swing.JRadioButton();
        frb1 = new javax.swing.JRadioButton();
        frb2 = new javax.swing.JRadioButton();
        frb3 = new javax.swing.JRadioButton();
        frb4 = new javax.swing.JRadioButton();
        fname = new javax.swing.JLabel();
        fcourse = new javax.swing.JLabel();
        fsubmit = new javax.swing.JButton();
        sflbcom = new javax.swing.JLabel();
        sflbimp = new javax.swing.JLabel();
        studentsignup = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        sturegno = new javax.swing.JTextField();
        stuname = new javax.swing.JTextField();
        signmail = new javax.swing.JTextField();
        signph = new javax.swing.JTextField();
        stupass = new javax.swing.JPasswordField();
        course = new javax.swing.JComboBox<>();
        branch = new javax.swing.JComboBox<>();
        validmail = new javax.swing.JLabel();
        validph = new javax.swing.JLabel();
        stusignup = new javax.swing.JButton();
        stulbn = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        users = new javax.swing.JFrame();
        jScrollPane5 = new javax.swing.JScrollPane();
        usertable = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        changepassword = new javax.swing.JFrame();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        cpname = new javax.swing.JTextField();
        cpregno = new javax.swing.JTextField();
        cpchange = new javax.swing.JButton();
        cpnew = new javax.swing.JPasswordField();
        cpcurrent = new javax.swing.JPasswordField();
        jLabel39 = new javax.swing.JLabel();
        cprepeat = new javax.swing.JPasswordField();
        cplbp = new javax.swing.JLabel();
        pslbsame = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        adminlogin.setMinimumSize(new java.awt.Dimension(800, 600));
        adminlogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                adminloginMouseMoved(evt);
            }
        });
        adminlogin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Admin Login");
        adminlogin.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Username: ");
        adminlogin.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Password: ");
        adminlogin.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        adminuser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adminlogin.getContentPane().add(adminuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 450, -1));

        adminpass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adminpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminpassActionPerformed(evt);
            }
        });
        adminlogin.getContentPane().add(adminpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 450, -1));

        sigu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sigu.setText("Sign In");
        sigu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguActionPerformed(evt);
            }
        });
        adminlogin.getContentPane().add(sigu, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 190, 50));

        studentlogin.setMinimumSize(new java.awt.Dimension(700, 600));
        studentlogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                studentloginMouseMoved(evt);
            }
        });
        studentlogin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText("Student Login");
        jLabel6.setMinimumSize(new java.awt.Dimension(700, 600));
        studentlogin.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Registration Number: ");
        studentlogin.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Password: ");
        studentlogin.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        studentuser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentlogin.getContentPane().add(studentuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 350, -1));

        studentpass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentlogin.getContentPane().add(studentpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 350, -1));

        stulog.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        stulog.setText("Login");
        stulog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stulogActionPerformed(evt);
            }
        });
        studentlogin.getContentPane().add(stulog, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 120, 50));

        fresherquestion.setMinimumSize(new java.awt.Dimension(800, 800));
        fresherquestion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fresherquestionMouseMoved(evt);
            }
        });
        fresherquestion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel18.setText("Question??");
        fresherquestion.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Name: ");
        fresherquestion.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Course: ");
        fresherquestion.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("E-Mail: ");
        fresherquestion.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Phone No.: ");
        fresherquestion.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("Question:");
        fresherquestion.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Description:");
        fresherquestion.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        qname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fresherquestion.getContentPane().add(qname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 530, -1));

        qcourse.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fresherquestion.getContentPane().add(qcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 530, -1));

        qmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qmailKeyReleased(evt);
            }
        });
        fresherquestion.getContentPane().add(qmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 530, -1));

        qphone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qphoneKeyReleased(evt);
            }
        });
        fresherquestion.getContentPane().add(qphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 530, -1));

        question.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fresherquestion.getContentPane().add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 650, -1));

        qdesc.setColumns(20);
        qdesc.setRows(5);
        qdesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qdescKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(qdesc);

        fresherquestion.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 650, 120));

        qsubmit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        qsubmit.setText("Submit");
        qsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qsubmitActionPerformed(evt);
            }
        });
        fresherquestion.getContentPane().add(qsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 660, 150, 50));

        qlbdesc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fresherquestion.getContentPane().add(qlbdesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 610, 150, 30));

        qlbmail.setText(" ");
        fresherquestion.getContentPane().add(qlbmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 280, 20));

        qlbphone.setText(" ");
        fresherquestion.getContentPane().add(qlbphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 250, 20));

        admin.setMinimumSize(new java.awt.Dimension(900, 800));
        admin.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                adminWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        admin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setText("Admin");
        admin.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Create Student Account");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        admin.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, -1, -1));

        feedbacktable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Reg. No.", "About", "Comment", "Suggestion ", "Rating"
            }
        ));
        jScrollPane4.setViewportView(feedbacktable);

        admin.getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 820, 260));
        admin.getContentPane().add(lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText("Show Users");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        admin.getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        freshertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Course", "E-Mail", "Phone", "Question", "Desc"
            }
        ));
        jScrollPane6.setViewportView(freshertable);

        admin.getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 820, 250));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel37.setText("FeedBack Data");
        admin.getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 340, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel38.setText("Questions by Freshers");
        admin.getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        student.setMinimumSize(new java.awt.Dimension(800, 800));
        student.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                studentMouseMoved(evt);
            }
        });
        student.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel25.setText("Student FeedBack");
        student.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("Chang Password");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        student.getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setText("Regno: ");
        student.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setText("About: ");
        student.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setText("Comment: ");
        student.getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setText("Improvement/Suggestions: ");
        student.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setText("Rating: ");
        student.getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, -1, -1));

        freg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        freg.setEnabled(false);
        student.getContentPane().add(freg, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 340, -1));

        fabout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        student.getContentPane().add(fabout, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 340, -1));

        fcomment.setColumns(20);
        fcomment.setRows(5);
        fcomment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fcommentKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(fcomment);

        student.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 340, -1));

        fimpro.setColumns(20);
        fimpro.setRows(5);
        fimpro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fimproKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(fimpro);

        student.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 340, 100));

        buttonGroup1.add(frb5);
        frb5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        frb5.setSelected(true);
        frb5.setText("5");
        student.getContentPane().add(frb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, -1, -1));

        buttonGroup1.add(frb1);
        frb1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        frb1.setText("1");
        student.getContentPane().add(frb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, -1, -1));

        buttonGroup1.add(frb2);
        frb2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        frb2.setText("2");
        student.getContentPane().add(frb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, -1, -1));

        buttonGroup1.add(frb3);
        frb3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        frb3.setText("3");
        student.getContentPane().add(frb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, -1, -1));

        buttonGroup1.add(frb4);
        frb4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        frb4.setText("4");
        student.getContentPane().add(frb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 520, -1, -1));

        fname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fname.setText("Name");
        student.getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 250, -1));

        fcourse.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fcourse.setText("Course ");
        student.getContentPane().add(fcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 180, -1));

        fsubmit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fsubmit.setText("Submit");
        fsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fsubmitActionPerformed(evt);
            }
        });
        student.getContentPane().add(fsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, 130, 50));

        sflbcom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sflbcom.setText(" ");
        student.getContentPane().add(sflbcom, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 150, -1));

        sflbimp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sflbimp.setText(" ");
        student.getContentPane().add(sflbimp, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 500, 160, 20));

        studentsignup.setMinimumSize(new java.awt.Dimension(700, 700));
        studentsignup.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                studentsignupMouseMoved(evt);
            }
        });
        studentsignup.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setText("Student SignUp");
        studentsignup.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Registration Number: ");
        studentsignup.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Name: ");
        studentsignup.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Course: ");
        studentsignup.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Branch: ");
        studentsignup.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("E-Mail: ");
        studentsignup.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Phone: ");
        studentsignup.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Password: ");
        studentsignup.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        sturegno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sturegno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sturegnoKeyReleased(evt);
            }
        });
        studentsignup.getContentPane().add(sturegno, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 370, -1));

        stuname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentsignup.getContentPane().add(stuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 370, -1));

        signmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        signmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                signmailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                signmailKeyReleased(evt);
            }
        });
        studentsignup.getContentPane().add(signmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 370, -1));

        signph.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        signph.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                signphKeyReleased(evt);
            }
        });
        studentsignup.getContentPane().add(signph, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 370, -1));

        stupass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentsignup.getContentPane().add(stupass, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 370, -1));

        course.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "B.Tech", "MCA", "BCA", "BSc", "BBA", "MBA" }));
        course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseActionPerformed(evt);
            }
        });
        studentsignup.getContentPane().add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 370, -1));

        branch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        branch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        studentsignup.getContentPane().add(branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 370, -1));
        studentsignup.getContentPane().add(validmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 340, 20));
        studentsignup.getContentPane().add(validph, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 340, 20));

        stusignup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        stusignup.setText("Sign Up");
        stusignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stusignupActionPerformed(evt);
            }
        });
        studentsignup.getContentPane().add(stusignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 130, 40));

        stulbn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        stulbn.setText(" ");
        studentsignup.getContentPane().add(stulbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 50, 20));

        users.setBackground(new java.awt.Color(255, 255, 255));
        users.setForeground(new java.awt.Color(240, 240, 240));
        users.setMinimumSize(new java.awt.Dimension(800, 500));
        users.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                usersWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        users.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Reg. No.", "Name", "Course", "Branch", "Email", "Phone"
            }
        ));
        jScrollPane5.setViewportView(usertable);

        users.getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 750, 270));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel31.setText("Users");
        users.getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        changepassword.setMinimumSize(new java.awt.Dimension(600, 800));
        changepassword.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                changepasswordMouseMoved(evt);
            }
        });
        changepassword.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel32.setText("Change Password");
        changepassword.getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel33.setText("Name: ");
        changepassword.getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 80, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setText("Reg. No.:");
        changepassword.getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel35.setText("Current Password: ");
        changepassword.getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel36.setText("New Password: ");
        changepassword.getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 150, -1));

        cpname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cpname.setEnabled(false);
        changepassword.getContentPane().add(cpname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 400, -1));

        cpregno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cpregno.setEnabled(false);
        changepassword.getContentPane().add(cpregno, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 400, -1));

        cpchange.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cpchange.setText("Change");
        cpchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpchangeActionPerformed(evt);
            }
        });
        changepassword.getContentPane().add(cpchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 140, 40));

        cpnew.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cpnew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cpnewKeyReleased(evt);
            }
        });
        changepassword.getContentPane().add(cpnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 400, -1));

        cpcurrent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        changepassword.getContentPane().add(cpcurrent, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 400, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel39.setText("Repeat Password: ");
        changepassword.getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 160, -1));

        cprepeat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        changepassword.getContentPane().add(cprepeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 400, -1));

        cplbp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cplbp.setText(" ");
        changepassword.getContentPane().add(cplbp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 280, 30));

        pslbsame.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        changepassword.getContentPane().add(pslbsame, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 270, 30));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("College Feedback System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 470, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feedback/VIT2.PNG"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Admin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 160, 50));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Student");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, 170, 50));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("Fresher");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 440, 170, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
adminlogin.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
studentlogin.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
fresherquestion.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void siguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguActionPerformed
try{
    Class.forName("java.sql.DriverManager");
    Connection con=(DriverManager.getConnection("jdbc:mysql://localhost:3306/feedback","root","root"));
    String un,pa,e;
    un=adminuser.getText();
    pa=new String( adminpass.getPassword());
    e="select * from admin where username= '"+un+"' and password= '"+pa+"'";
    Statement st= con.createStatement();
    ResultSet rs= st.executeQuery(e);
    if(rs.next()==true)
    {
        admin.setVisible(true);
    }
    else
    {
        JOptionPane.showMessageDialog(null, "Username or Password invalid... Try Again");
        adminuser.setText("");
        adminpass.setText("");
    }
}
catch(Exception e){
           JOptionPane.showMessageDialog(null, "Try Again");
 
}

        // TODO add your handling code here:
    }//GEN-LAST:event_siguActionPerformed

    private void adminpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminpassActionPerformed

    private void stulogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stulogActionPerformed
try{
    Class.forName("java.sql.DriverManager");
    Connection con=(DriverManager.getConnection("jdbc:mysql://localhost:3306/feedback","root","root"));
    String un,pa,e;
    un=studentuser.getText();
    pa=new String( studentpass.getPassword());
    e="select * from students where regno= '"+un+"' and password= '"+pa+"'";
    Statement st= con.createStatement();
    ResultSet rs= st.executeQuery(e);
    if(rs.next()==true)
    {
        
        student.setVisible(true);
        fname.setText(rs.getString("name"));
        fcourse.setText(rs.getString("course"));
        freg.setText(rs.getString("regno"));
    }
    else
    {
        JOptionPane.showMessageDialog(null, "Username or Password invalid... Try Again");
        studentuser.setText("");
        studentpass.setText("");
    }
}
catch(Exception e){
           JOptionPane.showMessageDialog(null, "Try Again");
 
}



        // TODO add your handling code here:
    }//GEN-LAST:event_stulogActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
studentsignup.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseActionPerformed
String selected= (String) course.getSelectedItem();

if(selected=="-")
{
    branch.removeAllItems();
    branch.addItem("-");
}
else if(selected=="B.Tech")
{
    branch.removeAllItems();
    branch.addItem("CSE");
    branch.addItem("EEE");
    branch.addItem("ECE");
    branch.addItem("MEC");    
}
else if(selected=="MCA")
{
    branch.removeAllItems();
    branch.addItem("-");
}
else if(selected=="BCA")
{
    branch.removeAllItems();
    branch.addItem("-");    
}
else if(selected=="BSc")
{
    branch.removeAllItems();
    branch.addItem("CHEM");
    branch.addItem("PHY");
    branch.addItem("CS");    
}
else if(selected=="BBA")
{
    branch.removeAllItems();
    branch.addItem("-");
}
else if(selected=="MBA")
{
    branch.removeAllItems();
    branch.addItem("Main");
    branch.addItem("Marketing");
    branch.addItem("Finance");
}






// TODO add your handling code here:
    }//GEN-LAST:event_courseActionPerformed

    private void signmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signmailKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_signmailKeyPressed

    private void signmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signmailKeyReleased
String st= signmail.getText();
if(st.contains("@")==true && st.contains(".")==true && st.contains(" ")==false)
{
    validmail.setText("");
}
else
{
    validmail.setText("Enter Correct Mail");
    stusignup.setEnabled(false);
    
}        // TODO add your handling code here:
    }//GEN-LAST:event_signmailKeyReleased

    private void signphKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signphKeyReleased
String st= signph.getText();
if(st.length()== 10)
{
    validph.setText("");
}
else
{
    validph.setText("Enter Correct Phone Number");
    stusignup.setEnabled(false);
}
for(int x=0;x<st.length();x++)
{
    int as= st.codePointAt(x);
    if(as<48 || as>57)
    {
         validph.setText("Enter Correct Phone Number");
         stusignup.setEnabled(false);
         break;
    }
}

        // TODO add your handling code here:
    }//GEN-LAST:event_signphKeyReleased

    private void stusignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stusignupActionPerformed
try{
    Class.forName("java.sql.DriverManager");
    Connection con=(DriverManager.getConnection("jdbc:mysql://localhost:3306/feedback","root","root"));
    String r,n,c,b,e,p,pa;
    r= sturegno.getText();
    n= stuname.getText();
    c= (String)course.getSelectedItem();
    b= (String)branch.getSelectedItem();
    e=signmail.getText();
    p=signph.getText();
    pa=new String (stupass.getPassword());
   
    String insert="insert into students values('"+r+"','"+n+"','"+c+"','"+b+"','"+e+"','"+p+"','"+pa+"')";
    
    Statement st=con.createStatement();
    st.executeUpdate(insert);
    JOptionPane.showMessageDialog(null, "Student Added");
    
    sturegno.setText("");
    stuname.setText("");
    course.setSelectedIndex(0);
    signmail.setText("");
    signph.setText("");
    stupass.setText("");
}
catch(Exception insert){
    JOptionPane.showMessageDialog(null, "Try with different values");
    
}
        // TODO add your handling code here:
    }//GEN-LAST:event_stusignupActionPerformed

    private void studentsignupMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsignupMouseMoved
int z1=sturegno.getText().length();
int z2=stuname.getText().length();
String s1=(String) course.getSelectedItem();
int z3=s1.length();
String s2=(String) branch.getSelectedItem();
int z4=s2.length();
int z5=signmail.getText().length();
int z6=signph.getText().length();
int z7=new String(stupass.getPassword()).length();

if(z1==10 && z2>0 && z3>1 && z5>0 && z6==10 && z7>0)
{
    stusignup.setEnabled(true);
}
else
{
    stusignup.setEnabled(false);
}

        // TODO add your handling code here:
    }//GEN-LAST:event_studentsignupMouseMoved

    private void qsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qsubmitActionPerformed
try{
    Class.forName("java.sql.DriverManager");
    Connection con=(DriverManager.getConnection("jdbc:mysql://localhost:3306/feedback","root","root"));
    String n,c,e,p,q,d;
    n=qname.getText();
    c=qcourse.getText();
    e=qmail.getText();
    p=qphone.getText();
    q=question.getText();
    d=qdesc.getText();
    
   
    String insert= "insert into freshers values('"+n+"','"+c+"','"+e+"','"+p+"','"+q+"','"+d+"')";
    Statement st=con.createStatement();
    st.executeUpdate(insert);
    JOptionPane.showMessageDialog(null, "Question Submitted...");
    
    qname.setText("");
    qcourse.setText("");
    qmail.setText("");
    qphone.setText("");
    question.setText("");
    qdesc.setText("");
   
    
}
catch(Exception e)
{
    
}
        // TODO add your handling code here:
    }//GEN-LAST:event_qsubmitActionPerformed

    private void fresherquestionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fresherquestionMouseMoved
 int x1= qname.getText().length();
 int x2= qcourse.getText().length();
 int x3= qmail.getText().length();
 int x4= qphone.getText().length();
 int x5= question.getText().length();
 int x6= qdesc.getText().length();
 if((x1 * x2 * x3 * x4 * x5 * x6)==0 || (x6>500) )
 {
     qsubmit.setEnabled(false);
 }
 else
 {
     qsubmit.setEnabled(true);
 }
 if(qlbphone.getText().length()==0 && qlbmail.getText().length() ==0)
 {
 } else {
     qsubmit.setEnabled(false);
        }
        // TODO add your handling code here:
        
        // TODO add your handling code here:
    }//GEN-LAST:event_fresherquestionMouseMoved

    private void studentMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentMouseMoved
int y1= fabout.getText().length();
int y2= fcomment.getText().length();
int y3= fimpro.getText().length();

if((y1 * y2 * y3)== 0)
{
    fsubmit.setEnabled(false);
}
else{
    fsubmit.setEnabled(true);
}
if(sflbcom.getText()=="Limit Exceeded" || sflbimp.getText()== "Limit Exceeded")
{
    fsubmit.setEnabled(false);
}

        // TODO add your handling code here:
    }//GEN-LAST:event_studentMouseMoved

    private void fsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fsubmitActionPerformed
try
{
    Class.forName("java.sql.DriverManager");
    Connection con=(DriverManager.getConnection("jdbc:mysql://localhost:3306/feedback","root","root"));
    String r,a,c,i,ra;
    r= freg.getText();
    a= fabout.getText();
    c= fcomment.getText();
    i= fimpro.getText();
    if(frb1.isSelected()==true)
    {
        ra="1";
    }
    else if(frb2.isSelected()==true)
    {
        ra="2";
    }
    else if(frb3.isSelected()==true)
    {
        ra="3";
    }
    else if(frb4.isSelected()==true)
    {
        ra="4";
    }
    else
    {
        ra="5";
    }
    
    String insert= "insert into feedback values('"+r+"','"+a+"','"+c+"','"+i+"','"+ra+"')";
    Statement st=con.createStatement();
    st.executeUpdate(insert);
    
    JOptionPane.showMessageDialog(null, "Feedback Submitted");
    
  
    fabout.setText("");
    fcomment.setText("");
    fimpro.setText("");
}
catch(Exception insert)
{
    JOptionPane.showMessageDialog(null, insert.getMessage());
}

        // TODO add your handling code here:
    }//GEN-LAST:event_fsubmitActionPerformed

    private void adminWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_adminWindowGainedFocus
DefaultTableModel model= (DefaultTableModel)
        feedbacktable.getModel();

        int rows= model.getRowCount();
        if(rows>0)
        {
            for(int i=0;i<rows;i++)
            {
                model.removeRow(0);
            }
        }
        
        try{
            Class.forName("java.sql.DriverManager");
            Connection con=(DriverManager.getConnection("jdbc:mysql://localhost:3306/feedback","root","root"));
            
            Statement st=con.createStatement();
            String e="select * from feedback";
            ResultSet rs=st.executeQuery(e);
            while(rs.next())
            {
                String regno= rs.getString("regno");
                String about= rs.getString("about");
                String comment= rs.getString("comment");
                String impro= rs.getString("impro");
                String rating= rs.getString("rating");
                
                model.addRow(new Object[]{regno,about,comment,impro,rating});
            }
        }
        catch(Exception e)
        {}
                
//______________________________________________________________________________

DefaultTableModel model1= (DefaultTableModel)
        freshertable.getModel();

        int row= model1.getRowCount();
        if(row>0)
        {
            for(int i=0;i<row;i++)
            {
                model1.removeRow(0);
            }
        }
        
        try{
            Class.forName("java.sql.DriverManager");
            Connection con=(DriverManager.getConnection("jdbc:mysql://localhost:3306/feedback","root","root"));
            
            Statement st=con.createStatement();
            String e="select * from freshers";
            ResultSet rs=st.executeQuery(e);
            while(rs.next())
            {
                String name= rs.getString("name");
                String course1= rs.getString("course");
                String email= rs.getString("email");
                String phone= rs.getString("phone");
                String que= rs.getString("question");
                String desc= rs.getString("description");
                
                model1.addRow(new Object[]{name,course1,email,phone,que,desc});
            }
        }
        catch(Exception e)
        {}
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_adminWindowGainedFocus

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
users.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void usersWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_usersWindowGainedFocus
DefaultTableModel model= (DefaultTableModel)
        usertable.getModel();

        int rows= model.getRowCount();
        if(rows>0)
        {
            for(int i=0;i<rows;i++)
            {
                model.removeRow(0);
            }
        }
        
        try{
            Class.forName("java.sql.DriverManager");
            Connection con=(DriverManager.getConnection("jdbc:mysql://localhost:3306/feedback","root","root"));
            
            Statement st=con.createStatement();
            String e="select * from students";
            ResultSet rs=st.executeQuery(e);
            while(rs.next())
            {
                String regno= rs.getString("regno");
                String name= rs.getString("name");
                String course= rs.getString("course");
                String branch= rs.getString("branch");
                String email= rs.getString("email");
                String phone= rs.getString("phone");
                
                
                model.addRow(new Object[]{regno,name,course,branch,email,phone});
            }
        }
        catch(Exception e)
        {}
                      // TODO add your handling code here:
    }//GEN-LAST:event_usersWindowGainedFocus

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
changepassword.setVisible(true);       
cpname.setText(fname.getText());
cpregno.setText(freg.getText());
    }//GEN-LAST:event_jButton7ActionPerformed

    private void cpchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpchangeActionPerformed
try{
    Class.forName("java.sql.DriverManager");
    Connection con=(DriverManager.getConnection("jdbc:mysql://localhost:3306/feedback","root","root"));
    String reg=cpregno.getText();
    String current= new String(cpcurrent.getPassword());
    String newp= new String(cpnew.getPassword());
    String e="Select * from students where regno= '"+reg+"' and password= '"+current+"'";
    Statement st1= con.createStatement();
    ResultSet rs= st1.executeQuery(e);
    if(rs.next()==true)
    {
        String q="update students set password= '"+newp+"' where regno='"+reg+"'";
        Statement st2= con.createStatement();
        st2.executeUpdate(q);
        JOptionPane.showMessageDialog(null, "Password Changed");
        cpcurrent.setText("");
        cpnew.setText("");
        
    }
    else
    {
        JOptionPane.showMessageDialog(null, "Wrong Password");
        cpcurrent.setText("");
        cpnew.setText("");
        cprepeat.setText("");
    }
    
}
catch(Exception e)
{
    
}
        
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_cpchangeActionPerformed

    private void adminloginMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminloginMouseMoved
int z1=adminuser.getText().length();
int z2=new String (adminpass.getPassword()).length();
if((z1*z2)==0)
{
    sigu.setEnabled(false);
}
else
{
    sigu.setEnabled(true);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_adminloginMouseMoved

    private void studentloginMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentloginMouseMoved
int z1=studentuser.getText().length();
int z2=new String (studentpass.getPassword()).length();
if((z1*z2)==0)
{
    stulog.setEnabled(false);
}
else
{
    stulog.setEnabled(true);
}

        // TODO add your handling code here:
    }//GEN-LAST:event_studentloginMouseMoved

    private void qdescKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qdescKeyReleased
int n= qdesc.getText().length();
qlbdesc.setText(n+"/500");
if(n>500)
{
    qlbdesc.setText("Limit Exceeded!!");
}


        // TODO add your handling code here:
    }//GEN-LAST:event_qdescKeyReleased

    private void qmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qmailKeyReleased
String mail=qmail.getText();
if(mail.contains("@")==true && mail.contains(".")==true && mail.contains(" ")==false)
{
    qlbmail.setText("");
}
else
{
    qlbmail.setText("Enter Valid Mail!!");
}

        // TODO add your handling code here:
    }//GEN-LAST:event_qmailKeyReleased

    private void qphoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qphoneKeyReleased
String st= qphone.getText();
if(st.length()== 10)
{
    qlbphone.setText("");
}
else
{
    qlbphone.setText("Enter Correct Phone Number");
}
for(int x=0;x<st.length();x++)
{
    int as= st.codePointAt(x);
    if(as<48 || as>57)
    {
         qlbphone.setText("Enter Correct Phone Number");
         break;
    }
}

        // TODO add your handling code here:
    }//GEN-LAST:event_qphoneKeyReleased

    private void fcommentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fcommentKeyReleased
int n=fcomment.getText().length();
if(n<500)
{
    sflbcom.setText(n+"/500");
}
else
{
    sflbcom.setText("Limit Exceeded");
}


        // TODO add your handling code here:
    }//GEN-LAST:event_fcommentKeyReleased

    private void fimproKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fimproKeyReleased
int n=fimpro.getText().length();
if(n<500)
{
    sflbimp.setText(n+"/500");
}
else
{
    sflbimp.setText("Limit Exceeded");
}        // TODO add your handling code here:
    }//GEN-LAST:event_fimproKeyReleased

    private void changepasswordMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changepasswordMouseMoved
int a1=new String(cpcurrent.getPassword()).length();
int a2=new String(cpnew.getPassword()).length();
int a3=new String(cprepeat.getPassword()).length();
if((a1*a2*a3)==0)
{
    cpchange.setEnabled(false);
}
else
{
    cpchange.setEnabled(true);
    cplbp.setText("");
}
String n1=new String(cpnew.getPassword());
String n2=new String(cprepeat.getPassword());
if(!n1.equals(n2))
{
    cpchange.setEnabled(false);
    cplbp.setText("Password Not Matching");
}

        // TODO add your handling code here:
    }//GEN-LAST:event_changepasswordMouseMoved

    private void sturegnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sturegnoKeyReleased
int x= sturegno.getText().length();
if(x!=10)
{
    stulbn.setText("X");
}
else
{
    stulbn.setText("");
}

        // TODO add your handling code here:
    }//GEN-LAST:event_sturegnoKeyReleased

    private void cpnewKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpnewKeyReleased
String old= new String(cpcurrent.getPassword());
String ne= new String(cpnew.getPassword());

if(old.equals(ne)==true)
{
    pslbsame.setText("New Passwords can't be same as previous one...");
}
else
{
    pslbsame.setText("");
}

        // TODO add your handling code here:
    }//GEN-LAST:event_cpnewKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame admin;
    private javax.swing.JFrame adminlogin;
    private javax.swing.JPasswordField adminpass;
    private javax.swing.JTextField adminuser;
    private javax.swing.JComboBox<String> branch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFrame changepassword;
    private javax.swing.JComboBox<String> course;
    private javax.swing.JButton cpchange;
    private javax.swing.JPasswordField cpcurrent;
    private javax.swing.JLabel cplbp;
    private javax.swing.JTextField cpname;
    private javax.swing.JPasswordField cpnew;
    private javax.swing.JTextField cpregno;
    private javax.swing.JPasswordField cprepeat;
    private javax.swing.JTextField fabout;
    private javax.swing.JTextArea fcomment;
    private javax.swing.JLabel fcourse;
    private javax.swing.JTable feedbacktable;
    private javax.swing.JTextArea fimpro;
    private javax.swing.JLabel fname;
    private javax.swing.JRadioButton frb1;
    private javax.swing.JRadioButton frb2;
    private javax.swing.JRadioButton frb3;
    private javax.swing.JRadioButton frb4;
    private javax.swing.JRadioButton frb5;
    private javax.swing.JTextField freg;
    private javax.swing.JFrame fresherquestion;
    private javax.swing.JTable freshertable;
    private javax.swing.JButton fsubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel pslbsame;
    private javax.swing.JTextField qcourse;
    private javax.swing.JTextArea qdesc;
    private javax.swing.JLabel qlbdesc;
    private javax.swing.JLabel qlbmail;
    private javax.swing.JLabel qlbphone;
    private javax.swing.JTextField qmail;
    private javax.swing.JTextField qname;
    private javax.swing.JTextField qphone;
    private javax.swing.JButton qsubmit;
    private javax.swing.JTextField question;
    private javax.swing.JLabel sflbcom;
    private javax.swing.JLabel sflbimp;
    private javax.swing.JTextField signmail;
    private javax.swing.JTextField signph;
    private javax.swing.JButton sigu;
    private javax.swing.JFrame student;
    private javax.swing.JFrame studentlogin;
    private javax.swing.JPasswordField studentpass;
    private javax.swing.JFrame studentsignup;
    private javax.swing.JTextField studentuser;
    private javax.swing.JLabel stulbn;
    private javax.swing.JButton stulog;
    private javax.swing.JTextField stuname;
    private javax.swing.JPasswordField stupass;
    private javax.swing.JTextField sturegno;
    private javax.swing.JButton stusignup;
    private javax.swing.JFrame users;
    private javax.swing.JTable usertable;
    private javax.swing.JLabel validmail;
    private javax.swing.JLabel validph;
    // End of variables declaration//GEN-END:variables
}
